services:
  - type: web
    name: lottery-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lottery-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: https://lottery-frontend.vercel.app,http://localhost:5173

databases:
  - name: lottery-db
    plan: free
    region: frankfurt